### ISSUE TITLE
405 Not allowed / Nginx error

### ISSUE THREAD

**Issue by GregTroar** [torrust/torrust-index#15]
Hi,

Not sure if I am doing anything wrong but first connection, I try to create a new account and get a 405 not allowed nginx error.
Anyone had this issue ?

Thanks

**Comment by WarmBeer** [comment]
Hey GregTroar,

Thanks for trying out Torrust! I'm sorry that you ran into a possible bug/issue. I'll investigate and get back to you ASAP!

**Comment by GregTroar** [comment]
Thank you

**Comment by WarmBeer** [comment]
Hey @GregTroar ,

I'm not sure what went wrong in the Nginx configuration. I've updated the installation instructions, including a new Nginx configuration template if you want to give that a go: https://torrust.com/installation/#nginx-configuration

**Comment by GregTroar** [comment]
Hi,

This is already what I had in Nginx, what did you change ?
Still not working here with error 405 when I try to create a new user

**Comment by WarmBeer** [comment]
I think the link to the backend is incorrect, could you `cd /opt/torrust/torrust/frontend` and then check the .env file?

**Comment by josecelano** [comment]
Hi @GregTroar, the application has changed a lot since you opened this issue. I'm going to close it, feel free to re-open it if you have the same problem with the latest version.
