### ISSUE TITLE
Federation

### ISSUE THREAD

**Issue by Zorlin** [torrust/torrust-index#21]
One thing I've been craving from BitTorrent sites can be summed up in one word - federation.

It would be extremely cool if there was a way to synchronise content between private torrent trackers that don't necessarily trust each other, so that for example music that lives on somesite.cd can also be found on othersite.cd.

Implementing this with torrents alone would be somewhat difficult as there needs to be a way for something to be seeded across both sites... [enter IPFS](https://github.com/torrust/torrust/issues/20). As IPFS web seeds are "global", someone seeding on one site can also provide content to peers on the other site via IPFS.

Actually getting federation working between sites is a hell of a task, but if we can begin thinking about how to accomplish it now and consider it as something to work towards in the future it could be a really powerful feature that differentiates Torrust from other tracker software.

**Comment by Zorlin** [comment]
Suggested ways we could actually implement federation:

* OrbitDB could be used to create a shared database
* Gun (https://gun.eco/)
* Redwood (https://github.com/redwood/redwood)
* ActivityPub pub/sub

**Comment by cgbosse** [comment]
Hi @Zorlin .
Thank you for your suggestion we have taken note of the issue and added it to our idea backlog for future development.

Also, stay tuned since we are going to be posting our roadmap with new issues during the coming weeks and we may need your input and help.

Thank you very much.
