### ISSUE TITLE
[admin] Setup Rulesets for `torrust-index-backend`

### ISSUE THREAD

**Issue by da2ce7** [torrust/torrust-index#299]
[Mirror from the torrust-tracker.](https://github.com/torrust/torrust-tracker/settings/rules)

### Filters:
`dependabot/**/*`
`releases/**/*`
`staging/**/*`

### Rules:
[(branches) [ * ; ! dependabot, ! releases, ! staging ] Deny Create; Deny Delete; Require Pull Request](https://github.com/torrust/torrust-tracker/settings/rules/87085)
[(branches) [ * ; ! dependabot, ! staging ] Deny Force Push; Require Status Checks](https://github.com/torrust/torrust-tracker/settings/rules/94237)
[(branches) [ * ] Required Signed](https://github.com/torrust/torrust-tracker/settings/rules/94133)
[(branches) [default] Require Deployment: coverage](https://github.com/torrust/torrust-tracker/settings/rules/87098)
[(branches) [releases] Bypass Create; Bypass Delete](https://github.com/torrust/torrust-tracker/settings/rules/86945)
[(branches) [releases] Deny Update; Require Deployment: dockerhub-torrust](https://github.com/torrust/torrust-tracker/settings/rules/94096)
[(branches) [staging] Bypass Create; Bypass Update; Bypass Delete; Bypass Force Push](https://github.com/torrust/torrust-tracker/settings/rules/90587)
[(tags) [ * ; ! v*.*.* ] Deny Create](https://github.com/torrust/torrust-tracker/settings/rules/87069)
[(tags) [ * ] Deny Update; Deny Delete; Deny Force Push; Require Signed](https://github.com/torrust/torrust-tracker/settings/rules/94135)
[(tags) [ v*.*.* ] Bypass Create](https://github.com/torrust/torrust-tracker/settings/rules/94130)

**Comment by josecelano** [comment]
Done https://github.com/torrust/torrust-index/rules
