### ISSUE TITLE
Rework Torrust Architecture Image

### ISSUE THREAD

**Issue by da2ce7** [torrust/torrust-index#343]
Before Merging:
- #338 

![Torrust Architecture](https://raw.githubusercontent.com/torrust/.github/main/img/torrust-architecture.webp)

Was present in the Readme. It has been removed because it was out-of-date.

Need to be updated.

**Comment by josecelano** [comment]
Hi @da2ce7, is it only because of the names?

![Torrust Tracker Architecture](https://github.com/torrust/torrust-index/assets/58816/d65c8241-d8c6-4526-a1b2-f1c47b77f5ec)
