### ISSUE TITLE
Rename Docker Deployment

### ISSUE THREAD

**Issue by da2ce7** [torrust/torrust-index#382]
The current name of the docker deployment: `dockerhub-torrust` could be renamed to: `oci-image` as a more generic alternative.

**Comment by josecelano** [comment]
> The current name of the docker deployment: `dockerhub-torrust` could be renamed to: `oci-image` as a more generic alternative.

Hi @da2ce7 that's the name of the environment where we deploy (publish) the images. We deploy the container image to DockerHub with the namespace/user `torrust`.

In the future, if we want to deploy the container image to a new container registry (like the [GitHub Packages registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry)) we will probably create a new environment `github-package-torrust` and new jobs in the workflows.

So I would keep it specific.
