### ISSUE TITLE
API license link should be relative

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index#457]
When you load the entrypoint for the API in the live demo:

https://index.torrust-demo.com/api/v1

You see a page like this:

![image](https://github.com/torrust/torrust-index/assets/58816/815275f3-e2aa-462f-b88b-679d354ed8f7)

The HTML link for the license is:

```html
<a href="/v1/about/license">license</a>
```

The link is broken because it redirects to:

https://index.torrust-demo.com/v1/about/license

The right link should be:

https://index.torrust-demo.com/api/v1/about/license

So the corrent `<a>` elements should be:

```html
<a href="v1/about/license">license</a>
```

The problem is we are using a subfolder for the API on the live demo and links should be relative.

**Comment by saras1212** [comment]
I can work on this!
