### ISSUE TITLE
API endpoint to verify if your token is legitimate or needs updating

### ISSUE THREAD

**Issue by ldpr** [torrust/torrust-index#52]
i'm automating a bunch of stuff and one pain point is there doesn't seem to be an API endpoint to verify if the token is good (as they rotate every few weeks).

Could we get something [like this](https://torrust.com/torrust-index/api/#get-userverifytoken) to verify API tokens please?

**Comment by WarmBeer** [comment]
Will work on it. The naming of that email verification endpoint is a bit confusing too.
