### ISSUE TITLE
CI error due to deprecated feature in dependency package ordered-multimap

### ISSUE THREAD

**Issue by mario-nt** [torrust/torrust-index#538]
We are getting this CI error due to the ordered-multimap package:

![image](https://github.com/torrust/torrust-index/assets/141633147/70d93999-b769-4a8f-ba4f-170506cc2342)

I think it has been fixed in the v0.7.0, but we are using the 0.6.0.

The dependency tree is the following:

Torrust Index -> config-rs v0.14.0 -> rust-ini v0.19.0 -> ordered-multimap 0.6.0.

The error is fixed in the v0.7.1 of ordered-multimap, but to get that newer version, the config-rs package needs to bump the rust-ini v0.19.0 to v0.20.0.

That dependency update is already present in the Cargo.toml file of the github repo for the config-rs package, but the crates.io package that we download in the project, still uses the v0.19.0.

I have already opened an issue in the config-rs project so they can update the crates.io package with the latest changes:
https://github.com/mehcode/config-rs/issues/548

**Comment by mario-nt** [comment]
One of the contributors answered telling that dependency change will be out in the next release of config, so we need to wait until the next version.

**Comment by josecelano** [comment]
This issue would be solved if [we migrate to Figment](https://github.com/torrust/torrust-index/issues/581).

**Comment by josecelano** [comment]
The `config` crate was removed [here](https://github.com/torrust/torrust-index/pull/592).
