### ISSUE TITLE
README: Test and Build badge 

### ISSUE THREAD

**Issue by cgbosse** [torrust/torrust-index#71]
Original image links extracted from the README:

- ![Test](https://github.com/torrust/torrust/actions/workflows/test.yml/badge.svg)
- ![Build](https://github.com/torrust/torrust/actions/workflows/build.yml/badge.svg)
I think that this may be the result of implementing the changes to the repository structure.

**Comment by WarmBeer** [comment]
Ah yeah, the test and build workflows are being moved to https://github.com/torrust/torrust-index-backend and https://github.com/torrust/torrust-index-frontend . So they don't have to be in this repository anymore.
