### ISSUE TITLE
Add config option to require signup invitation.

### ISSUE THREAD

**Issue by WarmBeer** [torrust/torrust-index#71]

**Comment by josecelano** [comment]
Before implementing this issue, take a look at the following:

- https://github.com/torrust/torrust-index-backend/issues/144#issuecomment-1602340005
- https://github.com/torrust/torrust-index-backend/issues/161
- https://github.com/torrust/torrust-index-backend/pull/238#discussion_r1279114823

We are still defining different types of configuration values and where to put them.

**Comment by WarmBeer** [comment]
Unassigned myself since this is a very old stale issue. We should discuss in the next meeting whether we still want this for the next major release.

**Comment by josecelano** [comment]
> Unassigned myself since this is a very old stale issue. We should discuss in the next meeting whether we still want this for the next major release.

OK @WarmBeer I'm going to close it. There is a [discussion](https://github.com/torrust/torrust-index/discussions/307). Once it's well defined we can concert the discussion into an issue and assign a milestone.
